### ISSUE TITLE
Roadmap for v0.7

### ISSUE THREAD

**Issue by raphaelvallat** [raphaelvallat/yasa#132]
**Ongoing PRs**:

- #127
- #130

**Remaining tasks**

- [ ] Use [Pooch](https://github.com/fatiando/pooch) to store and fetch datasets
- [ ] Update changelog
- [ ] Update FAQ, specifically section on how to export yasa.SleepStaging output to visualization softwares
- [ ] Add example on how to add yasa.Hypnogram instance to [raw.annotations](https://mne.tools/stable/generated/mne.Annotations.html)

```python
annotations = mne.Annotations(onset, duration, description)  
raw.set_annotations(annotations)  
```

- [ ] Update quickstart
- [ ] Major cleaning of notebooks
- [ ] Brainstorm the return type of `yasa.Hypnogra.upsample_to_data` — should it be a yasa.Hypnogram instance, an array of string or an array of int?

Forgot anything @remrama?

**Comment by remrama** [comment]
Looks great to me! If I think of anything else this is a good place to note it 👍
